platform :ios do
  lane :generate_plist do
    app_info(file: ENV["APP_PATH"])
    binary_info = JSON.parse(lane_context[SharedValues::APP_INFO])
    erb(
      template: "fastlane/ios_plist.erb",
      destination: "ios.plist",
      placeholders: {
        :name => binary_info["Name"],
        :release_version => binary_info["ReleaseVersion"],
        :identifier => binary_info["Identifier"],
        :app_url => "https://output.circle-artifacts.com/output/job/#{ENV["CIRCLE_WORKFLOW_JOB_ID"]}/artifacts/0/#{ENV["APP_PATH"]}"
      }
    )
  end

  lane :generate_page do
    app_info(file: ENV["APP_PATH"])
    binary_info = JSON.parse(lane_context[SharedValues::APP_INFO])
    erb(
      template: "fastlane/ios_page.erb",
      destination: "ios.html",
      placeholders: {
        :name => binary_info["Name"],
        :release_version => binary_info["ReleaseVersion"],
        :build_version => binary_info["BuildVersion"],
        :identifier => binary_info["Identifier"],
        :build_url => ENV["CIRCLE_BUILD_URL"],
        :branch => ENV["CIRCLE_BRANCH"],
        :plist_url => "https://output.circle-artifacts.com/output/job/#{ENV["CIRCLE_WORKFLOW_JOB_ID"]}/artifacts/0/ios.plist"
      }
    )
  end

  lane :generate_qr_code do
    url = "https://output.circle-artifacts.com/output/job/#{ENV["CIRCLE_WORKFLOW_JOB_ID"]}/artifacts/0/ios.html"
    code = qr_code(contents: url)
    FileUtils.cp(code['QR_CODE_PNG_PATH'], './qr_code.png')
  end
end

platform :android do
  lane :generate_page do
    app_info(file: ENV["APP_PATH"])
    binary_info = JSON.parse(lane_context[SharedValues::APP_INFO])
    erb(
      template: "fastlane/android_page.erb",
      destination: "android.html",
      placeholders: {
        :name => binary_info["Name"],
        :release_version => binary_info["ReleaseVersion"],
        :build_version => binary_info["BuildVersion"],
        :identifier => binary_info["Identifier"],
        :build_url => ENV["CIRCLE_BUILD_URL"],
        :branch => ENV["CIRCLE_BRANCH"],
        :app_url => "https://output.circle-artifacts.com/output/job/#{ENV["CIRCLE_WORKFLOW_JOB_ID"]}/artifacts/0/#{ENV["APP_PATH"]}"
      }
    )
  end

  lane :generate_qr_code do
    url = "https://output.circle-artifacts.com/output/job/#{ENV["CIRCLE_WORKFLOW_JOB_ID"]}/artifacts/0/android.html"
    code = qr_code(contents: url)
    FileUtils.cp(code['QR_CODE_PNG_PATH'], './qr_code.png')
  end
end
