platform :ios do
  lane :generate_page do
    app_info(file: "app/bitbar-ios-sample.ipa")
    puts "#{lane_context[SharedValues::APP_INFO]}"
  end
end

platform :android do
  lane :generate_page do
    app_info(file: "app/bitbar-sample-app.apk")
    puts "#{lane_context[SharedValues::APP_INFO]}"
    erb(
      template: "fastlane/android.erb",
      destination: "android.html",
      placeholders: {
        :build_url => ENV["CIRCLE_BUILD_URL"],
        :branch => ENV["CIRCLE_BRANCH"],
        :app_url => ENV["APP_URL"]
      }
    )
  end
end
